"""Deploy Qwen3.5 OpenAI-compatible server as a fully self-contained package.

Creates a deployment directory with:
  - Model IR files (int4_asym quantized)
  - Tokenizer files
  - Server code
  - OpenVINO + GenAI runtime (DLLs + Python bindings)
  - One-click setup and launch scripts

Usage:
  python deploy.py --model C:\\data\\models\\Huggingface\\Qwen3.5-4B --output D:\\deploy\\qwen3_5_4b
  python deploy.py --model ... --output ... --include-vl
  python deploy.py --model ... --output ... --genai-pkg ... --ov-bin ... --tbb-bin ...
"""

import argparse
import os
import shutil
import sys
import textwrap
from pathlib import Path

SERVING_DIR = Path(__file__).parent

# --- Model files -----------------------------------------------------------

MODEL_FILES_TEXT = [
    # IR (text-only, int4_asym gs128) — renamed to openvino_model.xml/bin
    ("qwen3_5_text_q4a_b4a_g128.xml", "openvino_model.xml"),
    ("qwen3_5_text_q4a_b4a_g128.bin", "openvino_model.bin"),
    # Tokenizer
    ("openvino_tokenizer.xml", None),
    ("openvino_tokenizer.bin", None),
    ("openvino_detokenizer.xml", None),
    ("openvino_detokenizer.bin", None),
    # Config
    ("config.json", None),
    ("tokenizer_config.json", None),
    ("tokenizer.json", None),
    ("chat_template.jinja", None),
    ("preprocessor_config.json", None),
    ("vocab.json", None),
    ("merges.txt", None),
]

MODEL_FILES_VL = [
    ("qwen3_5_text_vl_q4a_b4a_g128.xml", None),
    ("qwen3_5_text_vl_q4a_b4a_g128.bin", None),
    ("qwen3_5_vision.xml", None),
    ("qwen3_5_vision.bin", None),
    ("video_preprocessor_config.json", None),
]

SERVING_FILES = [
    "config.py",
    "schemas.py",
    "tool_parser.py",
    "engine.py",
    "vl_backend.py",
    "server.py",
    "bench.py",
    "requirements.txt",
    "README.md",
]

# --- Runtime files (platform-specific) ------------------------------------

# Windows: OpenVINO core DLLs
OV_DLLS_WIN = [
    "openvino.dll",
    "openvino_c.dll",
    "openvino_ir_frontend.dll",
    "openvino_intel_gpu_plugin.dll",
    "openvino_intel_cpu_plugin.dll",
    "openvino_auto_plugin.dll",
    "openvino_auto_batch_plugin.dll",
    "openvino_hetero_plugin.dll",
    "OpenCL.dll",
]

# Linux: OpenVINO core .so libs
OV_DLLS_LINUX = [
    "libopenvino.so",
    "libopenvino_c.so",
    "libopenvino_ir_frontend.so",
    "libopenvino_intel_gpu_plugin.so",
    "libopenvino_intel_cpu_plugin.so",
    "libopenvino_auto_plugin.so",
    "libopenvino_auto_batch_plugin.so",
    "libopenvino_hetero_plugin.so",
]

# Windows: openvino_genai package files
GENAI_PKG_FILES_WIN = [
    "py_openvino_genai.cp312-win_amd64.pyd",
    "py_openvino_genai.pyi",
    "openvino_genai.dll",
    "openvino_tokenizers.dll",
    "icudt70.dll",
    "icuuc70.dll",
]

# Linux: openvino_genai package files
GENAI_PKG_FILES_LINUX = [
    "py_openvino_genai.cpython-312-x86_64-linux-gnu.so",
    "py_openvino_genai.pyi",
    "libopenvino_genai.so",
    "libopenvino_tokenizers.so",
]

TBB_DLLS_WIN   = ["tbb12.dll", "tbbmalloc.dll", "tbbbind_2_5.dll"]
TBB_DLLS_LINUX = ["libtbb.so.12", "libtbbmalloc.so.2"]

import sys as _sys
IS_WIN = _sys.platform == "win32"
OV_DLLS_REQUIRED = OV_DLLS_WIN   if IS_WIN else OV_DLLS_LINUX
GENAI_PKG_FILES  = GENAI_PKG_FILES_WIN  if IS_WIN else GENAI_PKG_FILES_LINUX
TBB_DLLS         = TBB_DLLS_WIN   if IS_WIN else TBB_DLLS_LINUX

# --- Self-contained __init__.py for deployed package -----------------------

DEPLOYED_INIT_PY = textwrap.dedent('''\
    # Auto-generated by deploy.py — self-contained openvino_genai package.
    import os, sys
    _pkg_dir = os.path.dirname(__file__)
    if sys.platform == "win32":
        # Windows: add DLL directory so the loader finds bundled DLLs
        if hasattr(os, "add_dll_directory"):
            os.add_dll_directory(_pkg_dir)
    else:
        # Linux/macOS: pre-load core .so files into the process with RTLD_GLOBAL
        _ld = os.environ.get("LD_LIBRARY_PATH", "")
        os.environ["LD_LIBRARY_PATH"] = _pkg_dir + (":" + _ld if _ld else "")
        import ctypes
        for _lib in ["libopenvino.so", "libopenvino_genai.so", "libopenvino_tokenizers.so"]:
            _p = os.path.join(_pkg_dir, _lib)
            if os.path.exists(_p):
                ctypes.CDLL(_p, mode=ctypes.RTLD_GLOBAL)

    from .py_openvino_genai import (
        DecodedResults, EncodedResults, RawPerfMetrics, PerfMetrics,
        StreamerBase, get_version, StreamingStatus, TextStreamer,
    )
    from .py_openvino_genai import (
        LLMPipeline, draft_model, VLMPipeline,
        GenerationConfig, StopCriteria,
        Adapter, AdapterConfig,
        ChatHistory, TokenizedInputs, Tokenizer,
    )
    from .py_openvino_genai import (
        ContinuousBatchingPipeline, GenerationFinishReason,
        GenerationResult, GenerationStatus, SchedulerConfig,
    )

    __version__ = get_version()
''')


# --- Helpers ----------------------------------------------------------------

def _auto_detect_paths():
    """Try to auto-detect runtime paths from the current venv / build tree."""
    import sys
    try:
        import openvino_genai
        genai_pkg = Path(openvino_genai.__file__).parent
    except ImportError:
        genai_pkg = None

    # Dev build tree fallbacks (Windows and Linux)
    build_candidates = [
        Path(r"D:\chuansheng\src_code\explicit_modeling\openvino.genai\build\openvino_genai"),
        Path("/home/gta/chuansheng/src_code/openvino.genai/build/openvino_genai"),
    ]
    if genai_pkg is None:
        for c in build_candidates:
            if c.is_dir():
                genai_pkg = c
                break

    ov_bin = os.environ.get("OV_BIN_DIR")
    if ov_bin:
        ov_bin = Path(ov_bin)
    else:
        for candidate in [
            Path(r"D:\chuansheng\src_code\explicit_modeling\openvino\bin\intel64\Release"),
            Path("/home/gta/chuansheng/src_code/openvino/bin/intel64/Release"),
        ]:
            if candidate.is_dir():
                ov_bin = candidate
                break

    tbb_bin = None
    for candidate in [
        Path(r"D:\chuansheng\src_code\explicit_modeling\openvino\temp\Windows_AMD64\tbb\bin"),
        Path("/home/gta/chuansheng/src_code/openvino/temp/Linux_x86_64/tbb/lib"),
    ]:
        if candidate.is_dir():
            tbb_bin = candidate
            break

    return genai_pkg, ov_bin, tbb_bin


def _find_vl_exe() -> Path:
    """Auto-detect modeling_qwen3_5 binary from build tree (cross-platform)."""
    import sys
    candidates = [
        Path(r"D:\chuansheng\src_code\explicit_modeling\openvino.genai\build\bin\Release\modeling_qwen3_5.exe"),
        Path(r"D:\chuansheng\src_code\explicit_modeling\openvino.genai\build\bin\modeling_qwen3_5.exe"),
        Path("/home/gta/chuansheng/src_code/openvino.genai/build/bin/Release/modeling_qwen3_5"),
    ]
    for p in candidates:
        if p.is_file():
            return p
    return None


def _collect_file(src: Path, dst: Path, files: list, label: str = ""):
    """Add (src, dst) to files list with warning if missing."""
    if src.exists():
        files.append((src, dst))
    else:
        tag = f" [{label}]" if label else ""
        print(f"  WARN: missing{tag} {src.name}")


def main():
    parser = argparse.ArgumentParser(description="Deploy Qwen3.5 server — fully self-contained")
    parser.add_argument("--model", required=True, help="Source HF model directory with cached IR")
    parser.add_argument("--output", required=True, help="Output deployment directory")
    parser.add_argument("--include-vl", action="store_true", default=True, help="Include VL (vision) IR files (default: True)")
    parser.add_argument("--no-vl", action="store_true", help="Exclude VL (vision) IR files")
    parser.add_argument("--genai-pkg", help="openvino_genai site-packages dir (auto-detected)")
    parser.add_argument("--ov-bin", help="OpenVINO DLL directory (auto-detected)")
    parser.add_argument("--tbb-bin", help="TBB DLL directory (auto-detected)")
    parser.add_argument("--vl-exe", help="Path to modeling_qwen3_5.exe (auto-detected)")
    parser.add_argument("--dry-run", action="store_true", help="Show what would be copied")
    args = parser.parse_args()

    model_dir = Path(args.model)
    output_dir = Path(args.output)
    model_out = output_dir / "model"
    server_out = output_dir / "serving"
    runtime_out = output_dir / "runtime" / "openvino_genai"

    # Auto-detect runtime paths
    auto_genai, auto_ov, auto_tbb = _auto_detect_paths()
    genai_pkg = Path(args.genai_pkg) if args.genai_pkg else auto_genai
    ov_bin = Path(args.ov_bin) if args.ov_bin else auto_ov
    tbb_bin = Path(args.tbb_bin) if args.tbb_bin else auto_tbb

    include_vl = args.include_vl and not args.no_vl

    # Auto-detect VL exe
    vl_exe = Path(args.vl_exe) if args.vl_exe else _find_vl_exe()

    # Validate
    ir_xml = model_dir / "qwen3_5_text_q4a_b4a_g128.xml"
    if not ir_xml.exists():
        print(f"ERROR: IR not found: {ir_xml}")
        print("Generate IR first:")
        print(f"  modeling_qwen3_5 --model {model_dir} --mode text --prompt hi --output-tokens 2 --cache-model")
        sys.exit(1)

    if not genai_pkg or not genai_pkg.is_dir():
        print(f"ERROR: openvino_genai package not found. Use --genai-pkg or activate the right venv.")
        sys.exit(1)
    if not ov_bin or not ov_bin.is_dir():
        print(f"ERROR: OpenVINO DLL dir not found. Use --ov-bin or set OV_BIN_DIR env var.")
        sys.exit(1)
    if include_vl and (not vl_exe or not vl_exe.is_file()):
        print(f"ERROR: VL exe not found. Use --vl-exe or build modeling_qwen3_5 binary first.")
        print(f"  (searched: {vl_exe})")
        sys.exit(1)
    if include_vl:
        vl_ir = model_dir / "qwen3_5_vision.xml"
        if not vl_ir.exists():
            print(f"ERROR: VL IR not found: {vl_ir}")
            print("Generate VL IR first:")
            print(f"  modeling_qwen3_5 --model {model_dir} --mode vl --prompt hi --output-tokens 2 --cache-model --image <img>")
            sys.exit(1)

    print(f"Source paths:")
    print(f"  Model IR:      {model_dir}")
    print(f"  GenAI package: {genai_pkg}")
    print(f"  OV DLLs:       {ov_bin}")
    print(f"  TBB DLLs:      {tbb_bin or '(not found — may already be in OV dir)'}")
    if include_vl:
        print(f"  VL exe:        {vl_exe}")
    print()

    # --- Collect all files ---
    files = []

    # 1) Model files
    for src_name, dst_name in MODEL_FILES_TEXT:
        dst_name = dst_name or src_name
        _collect_file(model_dir / src_name, model_out / dst_name, files, "model")

    if include_vl:
        for src_name, dst_name in MODEL_FILES_VL:
            dst_name = dst_name or src_name
            _collect_file(model_dir / src_name, model_out / dst_name, files, "VL")

    # 2) Server code
    for f in SERVING_FILES:
        files.append((SERVING_DIR / f, server_out / f))

    # 3) Runtime: openvino_genai package files
    for f in GENAI_PKG_FILES:
        _collect_file(genai_pkg / f, runtime_out / f, files, "genai")

    # 4) Runtime: OpenVINO DLLs (into same dir so add_dll_directory finds them)
    for f in OV_DLLS_REQUIRED:
        _collect_file(ov_bin / f, runtime_out / f, files, "OV")

    # 5) Runtime: TBB DLLs
    if tbb_bin:
        for f in TBB_DLLS:
            _collect_file(tbb_bin / f, runtime_out / f, files, "TBB")

    # 6) VL exe (into runtime dir so it can find libs)
    if include_vl and vl_exe:
        exe_dst_name = "modeling_qwen3_5.exe" if IS_WIN else "modeling_qwen3_5"
        files.append((vl_exe, runtime_out / exe_dst_name))

    # Summary
    n_model = len([1 for _, d in files if str(d).startswith(str(model_out))])
    n_server = len([1 for _, d in files if str(d).startswith(str(server_out))])
    n_runtime = len([1 for _, d in files if str(d).startswith(str(runtime_out))])
    total_bytes = sum(s.stat().st_size for s, _ in files if s.exists())
    total_gb = total_bytes / (1024 ** 3)

    print(f"Deployment package: {output_dir}")
    print(f"  Model:   {n_model} files")
    print(f"  Server:  {n_server} files")
    print(f"  Runtime: {n_runtime} files (DLLs + Python bindings)")
    print(f"  Total:   {total_gb:.1f} GB")

    if args.dry_run:
        print("\nFiles:")
        for src, dst in files:
            sz = src.stat().st_size / (1024 ** 2) if src.exists() else 0
            print(f"  {dst.relative_to(output_dir)!s:55s}  ({sz:.1f} MB)")
        return

    # --- Copy ---
    print("\nCopying...")
    for d in [model_out, server_out, runtime_out]:
        d.mkdir(parents=True, exist_ok=True)

    for src, dst in files:
        if not src.exists():
            continue
        sz = src.stat().st_size / (1024 ** 2)
        print(f"  {dst.relative_to(output_dir)!s:55s}  ({sz:.1f} MB)")
        shutil.copy2(src, dst)
        if not IS_WIN and dst.suffix == "" and (src.stat().st_mode & 0o111):
            dst.chmod(dst.stat().st_mode | 0o111)  # preserve executable bit on Linux

    # 7) On Linux, create versioned symlinks for frontend .so files.
    #    OpenVINO's FrontEndManager discovers frontends by scanning for
    #    files named  libopenvino_*_frontend.so.<soversion>  (e.g. .so.2600).
    #    shutil.copy2 resolves symlinks, so we recreate the versioned names.
    if not IS_WIN:
        for f in sorted(runtime_out.glob("libopenvino_*_frontend.so")):
            # Detect soversion from the original build tree
            orig = ov_bin / f.name if ov_bin else None
            soversion = None
            if orig and orig.is_symlink():
                # e.g. libopenvino_ir_frontend.so -> libopenvino_ir_frontend.so.2600
                target = orig.resolve().parent / os.readlink(str(orig))
                # walk chain:  .so -> .so.2600 -> .so.2026.0.0
                while target.is_symlink():
                    target = target.resolve()
                # extract soversion from e.g. libopenvino_ir_frontend.so.2600
                for candidate in orig.parent.glob(f.stem + ".so.*"):
                    parts = candidate.name.split(".so.")
                    if len(parts) == 2 and parts[1].isdigit():
                        soversion = parts[1]
                        break
            if soversion is None:
                # Fallback: scan ov_bin for versioned siblings
                if ov_bin:
                    for candidate in ov_bin.glob(f.stem + ".so.*"):
                        parts = candidate.name.split(".so.")
                        if len(parts) == 2 and parts[1].isdigit():
                            soversion = parts[1]
                            break
            if soversion:
                link_name = f"{f.name}.{soversion}"
                link_path = runtime_out / link_name
                if not link_path.exists():
                    link_path.symlink_to(f.name)
                    print(f"  {str(link_path.relative_to(output_dir)):55s}  (symlink -> {f.name})")

    # 8) Generate self-contained __init__.py
    (runtime_out / "__init__.py").write_text(DEPLOYED_INIT_PY, encoding="utf-8")
    print(f"  {'runtime/openvino_genai/__init__.py':55s}  (generated)")

    # --- Scripts (both Windows and Linux) ---
    vl_exe_win  = r'--vl-exe "%~dp0runtime\openvino_genai\modeling_qwen3_5.exe"' if include_vl else ''
    vl_exe_lin  = '--vl-exe "$SCRIPT_DIR/runtime/openvino_genai/modeling_qwen3_5"' if include_vl else ''

    # Windows scripts
    setup_bat = output_dir / "setup.bat"
    setup_bat.write_text(textwrap.dedent(r"""
        @echo off
        REM One-time setup — creates venv and installs all dependencies
        cd /d %~dp0

        echo [1/3] Creating Python venv...
        python -m venv venv
        if not exist venv\Scripts\python.exe (
            echo ERROR: Failed to create venv. Ensure Python 3.12+ x64 is installed.
            exit /b 1
        )

        echo [2/3] Installing Python packages...
        venv\Scripts\pip.exe install --quiet -r serving\requirements.txt

        echo [3/3] Installing openvino_genai runtime...
        xcopy /E /I /Y runtime\openvino_genai venv\Lib\site-packages\openvino_genai\ >nul

        echo.
        echo === Setup complete ===
        echo Run start.bat to launch the server.
    """).lstrip(), encoding="utf-8")

    start_bat = output_dir / "start.bat"
    start_bat.write_text(textwrap.dedent(rf"""
        @echo off
        REM Qwen3.5 OpenAI API Server
        cd /d %~dp0
        set "PATH=%~dp0runtime\openvino_genai;%PATH%"
        cd serving
        "%~dp0venv\Scripts\python.exe" server.py --model "%~dp0model" --device GPU --port 8000 --model-name "Qwen3.5-4B" --quant none {vl_exe_win} %*
    """).lstrip(), encoding="utf-8")

    # Linux scripts
    setup_sh = output_dir / "setup.sh"
    setup_sh.write_text(textwrap.dedent("""\
        #!/usr/bin/env bash
        set -euo pipefail
        SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
        cd "$SCRIPT_DIR"

        echo "[1/3] Creating Python venv..."
        python3 -m venv venv

        echo "[2/3] Installing Python packages..."
        venv/bin/pip install --quiet -r serving/requirements.txt

        echo "[3/3] Installing openvino_genai runtime..."
        cp -a runtime/openvino_genai venv/lib/python3.*/site-packages/

        echo ""
        echo "=== Setup complete ==="
        echo "Run ./start.sh to launch the server."
    """), encoding="utf-8")
    setup_sh.chmod(0o755)

    start_sh = output_dir / "start.sh"
    start_sh.write_text(textwrap.dedent(f"""\
        #!/usr/bin/env bash
        set -euo pipefail
        SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
        export LD_LIBRARY_PATH="$SCRIPT_DIR/runtime/openvino_genai:${{LD_LIBRARY_PATH:-}}"
        cd "$SCRIPT_DIR/serving"
        "$SCRIPT_DIR/venv/bin/python" server.py \\
            --model "$SCRIPT_DIR/model" \\
            --device GPU --port 8000 \\
            --model-name "Qwen3.5-4B" --quant none \\
            {vl_exe_lin} "$@"
    """), encoding="utf-8")
    start_sh.chmod(0o755)

    # --- Done ---
    runtime_mb = sum(
        s.stat().st_size for s, d in files
        if s.exists() and str(d).startswith(str(runtime_out))
    ) / (1024 ** 2)

    print(f"\n{'=' * 60}")
    print(f"  Deployment package created: {output_dir}")
    print(f"  model/   — {total_gb:.1f} GB (IR + tokenizer)")
    print(f"  serving/ — server code")
    print(f"  runtime/ — {runtime_mb:.0f} MB (OpenVINO + GenAI libs)")
    print(f"{'=' * 60}")
    print(f"\nDeploy to target machine:")
    print(f"  1. Copy {output_dir} to target")
    print(f"  Linux:   ./setup.sh  then  ./start.sh")
    print(f"  Windows: setup.bat   then  start.bat")



if __name__ == "__main__":
    main()
